### ISSUE TITLE
Trying to figure out code provenance

### ISSUE THREAD

**Issue by lvh-dd** [jcmdev0/gpgagent#1]
First off, thanks for making this a separate package. Much appreciated. I'm trying to figure out the code provenance here. It appears that when it got into Trousseau, it acquired a Google copyright header. But that file doesn't have any contributors outside of @Oleiade, and, he doesn't work at Google anymore (perhaps he used to)?

**Comment by jcmdev0** [comment]
It looks like @Oleiade took parts of it from  https://github.com/camlistore/camlistore.  I don't see any evidence that @Oleiade is/was part of Google. 

That file appears to have originated with a google copyright and camlistore's @bradfitz is a Google employee.
https://github.com/camlistore/camlistore/commit/2ac8794abe007be87f465b0b3e7c69aa734e03f2

**Comment by tcr-ableton** [comment]
If that can help, I think the gpgagent code is indeed extracted from camlistore :-)

**Comment by bradfitz** [comment]
Yup, I wrote it.
